hydra:
  run:
    dir: "hydra_logs"
  output_subdir: ${now:%Y-%m-%d_%H-%M-%S}

defaults:
  - _self_
  - data: data
  - model: model
  - train: train


seed: 42
experiment_name: gemma-3-4b--${train.task}--no-quant--eng


wandb:
  project: bidirectional-decoder
  entity: havlytskyi-thesis
  name: ${experiment_name}
#  log_model: all
